[package]
name = "TcpChat"
version = "0.1.0"
edition = "2024"

[dependencies]
base64 = "0.22.1"
chrono = "0.4.42"
rand = "0.9.2"
rsa = "0.9.9"
serde = { version = "1.0", features = ["derive"] }
sha2 = "0.10.9"
term_size = "0.3.2"
toml = "0.8"

